# Generated by Django 5.2.5 on 2026-03-01 21:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo_image'),
        ),
    ]
