# Generated by Django 5.2.5 on 2026-03-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_achievement_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-created_at']},
        ),
    ]
