# Generated by Django 5.2.5 on 2026-03-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_team'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teams', '0002_achievement_created_by'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['team'], name='accounts_cu_team_id_04a6b9_idx'),
        ),
    ]
