# Generated by Django 5.2.5 on 2026-03-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_accounts_cu_team_id_04a6b9_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at']},
        ),
    ]
